// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2WnPgL_C-g97ISST5Gu08mHtT60iDey4',
    appId: '1:155537738977:web:1235ed7f0ee2b9f6bbfba0',
    messagingSenderId: '155537738977',
    projectId: 'chatapp-9f461',
    authDomain: 'chatapp-9f461.firebaseapp.com',
    storageBucket: 'chatapp-9f461.appspot.com',
    measurementId: 'G-GXYG220CPP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkgikSzAOHeW3RYXm31R0vASi2apcVurw',
    appId: '1:155537738977:android:a116aed11e9fefc9bbfba0',
    messagingSenderId: '155537738977',
    projectId: 'chatapp-9f461',
    storageBucket: 'chatapp-9f461.appspot.com',
  );
}
